name: S3 Deploy
on:
  push:
    branches:
      - main

env:
  BUCKET_NAME : ${{ secrets.S3_BUCKET }}
  AWS_REGION : ${{ secrets.S3_BUCKET_REGION }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GH_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync files to the S3
        run: |
          aws s3 sync --exclude ".git*" --delete . s3://${{ secrets.S3_BUCKET }}
