name: S3 Deploy
on:
  push:
    branches:
      - main

# Need to clean environment - aws config doesn't work well otherwise with assume role'
env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_S3_BUCKET_REGION }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    name: S3 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_S3_BUCKET_REGION }}
          role-to-assume: ${{ vars.AWS_GH_OIDC_ROLE }}

      - name: Sync files to the S3
        run: |
          aws s3 sync --delete src s3://${{ vars.AWS_S3_BUCKET }}

      - name: Invalidate CloudFront distribution cache and wait
        run: >
          aws cloudfront create-invalidation
          --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          --paths "/"
          --output json | tee cf_inv.json

          echo Waiting for Invalidation: $(cat cf_inv.json | jq -r .Invalidation.Id)

          aws cloudfront wait invalidation-completed
          --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          --id $(cat cf_inv.json | jq -r .Invalidation.Id)
